module.exports = {
  min: require('./min'),
  max: require('./max'),
  between: require('./between'),
  checked: require('./checked'),
  object: require('./object'),
  array: require('./array'),
  boolean: require('./boolean'),
  alpha_numeric: require('./alpha_numeric'),
  alpha: require('./alpha'),
  email: require('./email'),
  alpha_dash: require('./alpha_dash'),
  in_array: require('./in_array'),
  not_in: require('./not_in'),
  json: require('./json'),
  ip: require('./ip'),
  url: require('./url'),
  equals: require('./equals'),
  not_equals: require('./not_equals'),
  starts_with: require('./starts_with'),
  ends_with: require('./ends_with'),
  date: require('./date'),
};
